Update to Logistics admin, General moderation buttons
ArcaniteSolutions/truffe2 pull request #21
Opened 2017-11-16 10:20 UTC by CedricCook

Update to 

- Logistics: Reservations admin view
- Logistics: Reservation view (supply list)
- Logistics: Reservations public view
- General moderation buttons redo
- General column spacing changes

2017-11-16 10:23 UTC, CedricCook commented
Overall UI change:

**Before**
<img width="1354" alt="truffe_log_before" src="https://user-images.githubusercontent.com/1197161/32886267-74b9b8f4-cac0-11e7-9fa8-eb1d967b52ec.png">

**After**
<img width="1195" alt="truffe_log_post" src="https://user-images.githubusercontent.com/1197161/32886268-74d4513c-cac0-11e7-918a-1812d8761ab8.png">

2017-11-20 20:44 UTC, the-glu requested changes

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +        # return u' '.join([u'{}{}'.format(u'{} * '.format(line.quantity) if line.quantity > 1 else '', line.supply.title) for line in self.lines.order_by('order')])
Enlève ce qui sert à rien, au pire y'a l'historique git ;)

2017-11-20 20:44 UTC, the-glu commented on truffe2/templates/datatables.html
> +                    {% if force_last_width %}{ "sWidth": "73px", "aTargets": [{{force_last_width}}] }, {% endif %}
C'est vachement global ça. T'es sur de vouloir 2-ligner les boutons un peu partout ? C'est moins comptact

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +            '2': '25%',
Pep8 sur tous les commentaires dans les forced width ( `,[espace][espace]#[espace]commentaire`)

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +        line_link_list = '<ul class="supply-items">'
python 2, il manque un u

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +        line_link_list += '</ul>'
python 2, il manque un u

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +            line_link_list += '<li><span>'
Faudrait remplacer les `+=` avec des format

2017-11-20 20:44 UTC, the-glu commented on truffe2/logistics/models.py
> +            retour += u'<li><span>'
+= format ici aussi

2017-11-21 10:53 UTC, CedricCook commented on truffe2/templates/datatables.html
> +                    {% if force_last_width %}{ "sWidth": "73px", "aTargets": [{{force_last_width}}] }, {% endif %}
À la base je voulais les mettre sur 2 lignes partout oui, par contre j'ai changé d'autres trucs pour quand meme les laisser sur une ligne.

2017-11-21 21:33 UTC, the-glu requested changes
Encore le coup des += qui traine

2017-11-22 21:00 UTC, the-glu approved these changes

2017-11-22 21:01 UTC, merged