Convention de prêt auto et typos/visuels
ArcaniteSolutions/truffe2 pull request #24
Opened 2018-02-12 11:47 UTC by JonathanCollaud

2018-03-14 21:48 UTC, the-glu requested changes

2018-03-14 21:48 UTC, the-glu commented on truffe2/logistics/templates/logistics/supplyreservation/pdf.html
> +    {%if not supplyreservation.unit%}
Espaces tousa

2018-03-14 21:48 UTC, the-glu commented on truffe2/logistics/templates/logistics/supplyreservation/show.html
> +    {% if related_mode %}
C'est normal que y'a pas de test sur le droit de SHOW ici ? 

(Je suis pas sur que ça soit pas déjà fait dans le truc que tu extends)

2018-04-19 15:16 UTC, JonathanCollaud reviewed
Dans les autres fichiers qui utilisent le block bonus_buttons, il n'y a pas de check de permissions non plus. Et comme dit ci-dessus, s'il a le droit de voir la page related, il a le droit de voir la convention de pret aussi

2018-04-19 15:16 UTC, JonathanCollaud commented on truffe2/logistics/templates/logistics/supplyreservation/show.html
> +    {% if related_mode %}
D'après ce que j'ai compris, le fait que ça soit related suffit à limiter aux internes de l'unité qui prête le matériel, et si le dude n'a pas les droits logistique, il n'est pas censé avec accès aux "réservations de me mon matériel"

2018-04-19 18:13 UTC, the-glu requested changes

2018-04-19 18:13 UTC, the-glu commented on truffe2/communication/templates/communication/displayreservation/edit.html
> +        var display = $('#id_display').parent().parent().remove();
il faudrait mettre ça dans le block ready en bas histoire d'être sur que la page est chargée

2018-04-19 18:13 UTC, the-glu commented on truffe2/communication/templates/communication/displayreservation/edit.html
> +        var display = $('#id_display').parent().parent().remove();
(Avant le début de la fonction actuelle qui fait aussi des choses sur iddisplay)

2018-04-19 18:13 UTC, the-glu commented on truffe2/communication/templates/communication/displayreservation/show.html
> +        {% if forloop.first %}
T'es plus dans une boucle for là non ?

2018-04-19 18:13 UTC, the-glu commented on truffe2/communication/views.py
> +from generic.templatetags.generic_extras import html_check_and_safe
Y'a pleins de nouveaux includes dans le fichier mais tu t'en sert pas oO ?

2018-04-19 18:13 UTC, the-glu commented on truffe2/logistics/models.py
> +from app.utils import get_current_unit
même remarque aussi ici sur getcurrentunit pas utilisé

2018-04-19 18:13 UTC, the-glu commented on truffe2/logistics/templates/logistics/supplyreservation/show.html
> +    {% if related_mode %}
ok

2018-04-23 15:20 UTC, JonathanCollaud commented on truffe2/communication/templates/communication/displayreservation/edit.html
> +        var display = $('#id_display').parent().parent().remove();
La même dans truffe2/logistics/templates/logistics/roomreservation/edit.html
Je regarde comment faire et je change les deux du coup

2018-04-23 15:27 UTC, JonathanCollaud commented on truffe2/communication/templates/communication/displayreservation/show.html
> +        {% if forloop.first %}
nop merci, corrigé

2018-04-23 15:29 UTC, JonathanCollaud commented on truffe2/communication/views.py
> +from generic.templatetags.generic_extras import html_check_and_safe
cleaned

2018-04-23 15:30 UTC, JonathanCollaud commented on truffe2/logistics/models.py
> +from app.utils import get_current_unit
tout propre

2018-04-23 15:30 UTC, JonathanCollaud commented on truffe2/logistics/templates/logistics/supplyreservation/pdf.html
> +    {%if not supplyreservation.unit%}
checked

2018-04-23 15:48 UTC, JonathanCollaud commented on truffe2/communication/templates/communication/displayreservation/edit.html
> +        var display = $('#id_display').parent().parent().remove();
J'ai cherché dans les autres edit.html, pas trouvé de block ready ^^' T'es sur qu'il est nécessaire et si oui où est-ce qu'il est implémenté?

2018-04-24 19:46 UTC, the-glu commented on truffe2/communication/templates/communication/displayreservation/edit.html
> +        var display = $('#id_display').parent().parent().remove();
Par block ready, je voulais dire dans le `$(function () { ici; reste du code; }`

2018-04-27 16:11 UTC, merged