Add a validation process for outbound factures
ArcaniteSolutions/truffe2 pull request #32
Opened 2020-04-18 09:15 UTC by TeoGoddet

2020-04-24 22:25 UTC, the-glu requested changes

2020-04-24 22:25 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '2_ask_accord': [('2_accord', 'fa fa-check', _(u'Donnez l\'accord')),],
Donner ?

2020-04-24 22:25 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '2_ask_accord': [('2_accord',  _(u'Donnez l\'accord')),],
Pareil

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/mails/invoices_accepted.html
> +{% trans 'La facture "' %}{{notification.linked_object}}{% trans '" a été acceptée.' %}
utilise des blocktrans

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/mails/invoices_accepted.html
> +{% trans "Il faut l'envoyez !" %}</li>
er

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/mails/invoices_to_correct.html
> +{% trans "La facture contient des erreurs à corrigée" %}: <span class="text-primary">{{notification.linked_object}}</span>!
corriger

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/invoices_accepted.html
> +{% trans "Il faut l'envoyez !" %}</li>
er

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/center/message/invoices_to_correct.html
> +{% trans "La facture contient des erreurs à corrigée" %}: <span class="text-primary">{{notification.linked_object}}</span>!
er

2020-04-24 22:25 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/center/message/invoices_accepted.html
> +{% trans "La facture a été acceptée, il faut l'envoyez" %}
er

2020-04-24 22:25 UTC, the-glu commented on truffe2/accounting_tools/templates/accounting_tools/invoice/show.html
> +   {% if obj.status != '0_preparing' and obj.status != '0_correct' and obj.status != '1_need_bvr' and obj.status != '2_ask_accord' and obj.status != '5_cancelled' %}
Tu veux pas juste mettre l'autre tatus ? Aussi pourquoi cacher la facture ?

Et tu met pas de check dans la vue, du coup on peut quiand même la download

+ Tab qui manque

2020-04-24 22:25 UTC, the-glu commented on truffe2/accounting_tools/templates/accounting_tools/invoice/list_json.html
> +   {% if obj.status != '0_preparing' and obj.status != '0_correct' and obj.status != '1_need_bvr' and obj.status != '2_ask_accord' and obj.status != '5_cancelled' %}
Tu veux pas juste mettre l'autre tatus ? Aussi pourquoi cacher la facture ?

Et tu met pas de check dans la vue, du coup on peut quiand même la download

+ Tab qui manque

2020-05-30 14:12 UTC, TeoGoddet commented on truffe2/accounting_tools/templates/accounting_tools/invoice/show.html
> +   {% if obj.status != '0_preparing' and obj.status != '0_correct' and obj.status != '1_need_bvr' and obj.status != '2_ask_accord' and obj.status != '5_cancelled' %}
Le but est d'évitez que des facture partent sans avoir été validé car on s'est rendu compte qu'il y avait beaucoup d'erreurs dans nos factures, j'ai changer la vue aussi

2020-06-09 08:03 UTC, TeoGoddet commented on truffe2/notifications/templates/notifications/species/mails/invoices_accepted.html
> +{% trans 'La facture "' %}{{notification.linked_object}}{% trans '" a été acceptée.' %}
Done

2020-06-09 08:07 UTC, TeoGoddet commented
Tu peut relire celle ci aussi

2020-07-24 11:39 UTC, the-glu requested changes

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '2_accord': _(u'Il faut envoyez la facture'),
envoyer

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +	    '1_need_bvr': ['0_correct'],
tab

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '3_sent': _(u'Envoyée / paiement en attente'),
Vu que tu change les numéros faut migrer la DB

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '3_sent': _(u'Envoyée / paiement en attente'),
(Numéro = keys)

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/templates/accounting_tools/invoice/list_json.html
> +    	<a href=\"{% url 'accounting_tools.views.invoice_pdf' elem.pk %}{% trans "Facture" %} {{elem.title|urlencode}} - {{elem.get_reference}}.pdf?{% if upk_noswitch %}&_upkns=_{% endif %}{% if from_re
Tabs

2020-07-24 11:39 UTC, the-glu commented on truffe2/accounting_tools/views.py
> +    if invoice.status not in ['2_accord', '3_sent', '4_archived'] and (not request.user.is_superuser or not invoice.rights_in_root_unit(request.user, 'SECRETARIAT')):
Met ça dans un droit, et test le droit dans ton template, c'est plus maintenable et évite d'avoir des droit différents dans le template et la vue (ce qui es le cas là)

2020-07-24 11:39 UTC, the-glu commented on truffe2/main/templates/main/box/invoices.html
> +	    {% for invoice in invoices_attente_accord %}
tab

2020-07-24 11:39 UTC, the-glu commented on truffe2/notifications/templates/notifications/species/center/message/invoices_accepted.html
> +{% trans "La facture a été acceptée, il faut l'envoyer" %}
Met le lien comme dans à corriger non ?

2020-07-25 15:15 UTC, TeoGoddet commented on truffe2/accounting_tools/models.py
> +            '3_sent': _(u'Envoyée / paiement en attente'),
See https://github.com/ArcaniteSolutions/truffe2/pull/32/files#diff-7dc6287daa972e5bb68c2b73453344df

2020-08-23 21:28 UTC, TeoGoddet commented
@the-glu ca doit être pas mal, tu peut y jeter un oeil.

2020-08-28 08:30 UTC, the-glu commented on truffe2/accounting_tools/models.py
> +            '3_sent': _(u'Envoyée / paiement en attente'),
My bad, le fichier était fermé ^^

2020-08-28 08:31 UTC, merged