Catch errors on notif mail sending
ArcaniteSolutions/truffe2 pull request #37
Opened 2020-05-15 16:18 UTC by TeoGoddet

Avoid one problematic (non existent per instance) to block the whole notification command

2020-05-15 19:47 UTC, the-glu requested changes

2020-05-15 19:47 UTC, the-glu commented on truffe2/notifications/management/commands/process_notifications.py
> +                        print("Catched error while sending notification : {}".format(e))
`notification: {}` en anglais (*2)

2020-06-01 19:36 UTC, the-glu requested changes
Au lieu de print, est-ce que tu peux send via sentry ?

(Et si y'a vraiement besion de print, print que si c'est en debug=True, et sentry dans tous les cas)

(Attention à ne sentry que si sentry est ok)

Aussi, tu peux mettre ça dans send_templated_mail non ?

2020-06-09 07:59 UTC, TeoGoddet commented
J'ai fait une nouvelle version qui utilise le logging de django ,tu en pense quoi ?

2020-07-24 11:44 UTC, merged