Clean up display mode for reservations with multiple items
ArcaniteSolutions/truffe2 pull request #7
Opened 2017-01-04 17:39 UTC by CedricCook

Fix the way supply multiple reservations are shown, to make the RespLog life's easier!

Go from: 
![image](https://cloud.githubusercontent.com/assets/1197161/21652439/ef140fb2-d2ac-11e6-888e-6b36004e342b.png)

To:

![image](https://cloud.githubusercontent.com/assets/1197161/21652444/f4723362-d2ac-11e6-85f2-c594042fe8b5.png)

2017-01-04 17:52 UTC, the-glu commented
Tu pourrais mettre le 1 * avant et les sorts alphabétiquement temps qu'a faire ? ^^

2017-01-04 18:21 UTC, CedricCook commented
Ils sont sort par leur order dans la réservation (en tout cas c'est ton code que j'ai repris ;P)
Et puis pour les chiffres avant, oui totalement je voulais faire à la base !

2017-01-05 07:17 UTC, lionel-martin requested changes
Juste un détail

2017-01-05 07:17 UTC, lionel-martin commented on truffe2/logistics/models.py
> +            line_link_list += u'<a href="{}">{}{}</a>'.format(reverse('logistics.views.supply_show', args=(line.supply.pk,)), line.supply, u' * {}'.format(line.quantity))
Ta perdu la feature de pas montrer le nombre si c'est 1

2017-01-05 08:18 UTC, CedricCook commented on truffe2/logistics/models.py
> +            line_link_list += u'<a href="{}">{}{}</a>'.format(reverse('logistics.views.supply_show', args=(line.supply.pk,)), line.supply, u' * {}'.format(line.quantity))
C'est fait exprès. C'est plus cohérent dans les prêts de matos d'avoir toujours quantité + nom de matos. En tout cas les 3 dudes qui s'occupent des prêts cette année ont demandé ce feature. Ça te va ?

2017-01-05 08:21 UTC, lionel-martin approved these changes

2017-01-05 11:49 UTC, merged